---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: ubuntu-14.04

suites:
  - name: default-package
    run_list:
      - recipe[apt]
      - recipe[foreman]

  - name: default-source
    run_list:
      - recipe[apt]
      - recipe[foreman]
    attributes:
      install_method: source
