---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver:
       customize:
         memory: 1024

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[foreman]
      - recipe[foreman::proxy]
    attributes:
      postgresql:
        password:
          postgres: toor
