---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero
  driver:
    vm_hostname: 'vagrant.example'

platforms:
  - name: ubuntu-14.04
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[foreman]
      - recipe[foreman::proxy]
    attributes:
      postgresql:
        password:
          postgres: toor
