---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver:
       customize:
         memory: 2048

suites:
  - name: default
    driver:
      network:
        - - private_network
          - ip: 172.16.0.2
    run_list:
      - recipe[apt]
      - recipe[foreman]
        #- recipe[foreman::proxy]
    attributes:
      postgresql:
        password:
          postgres: toor
      foreman-proxy:
        dhcp_range: '172.16.0.10 172.16.0.20'
