AllCops:
  Include:
    - metadata.rb
    - '**/Gemfile'
    - attributes/**/*
    - definitions/**/*
    - libraries/**/*
    - providers/**/*
    - recipes/**/*
    - resources/**/*
    - spec/**/*
    - test/**/*
  Exclude:
    - cookbooks/**/*
    - vendor/**/*

NumericLiterals:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/LineLength:
  Exclude:
    - spec/**/*
    - libraries/matchers.rb
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
