AllCops:
  DisplayCopNames: true
  Exclude:
    - cookbooks/**/*
    - vendor/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - recipes/proxy_tftp.rb
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Max: 70
Metrics/LineLength:
  Exclude:
    - spec/**/*
    - test/**/*
    - libraries/matchers.rb
Metrics/MethodLength:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/SymbolArray:
  Enabled: false
