AllCops:
  Exclude:
    - cookbooks/**/*
    - vendor/**/*

NumericLiterals:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/LineLength:
  Exclude:
    - spec/**/*
    - test/**/*
    - libraries/matchers.rb
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Max: 70
